// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6-KMcK1N936hqJhDg9fk72vyRBOCeUU',
    appId: '1:959851867881:web:f870808c8171da6f794a78',
    messagingSenderId: '959851867881',
    projectId: 'toy-unity',
    authDomain: 'toy-unity.firebaseapp.com',
    storageBucket: 'toy-unity.appspot.com',
    measurementId: 'G-MMETQW7FQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoMDv0Es57u1TueDwuN4FoyAr9Bd60X84',
    appId: '1:959851867881:android:e014c9be76ddd353794a78',
    messagingSenderId: '959851867881',
    projectId: 'toy-unity',
    storageBucket: 'toy-unity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQHC_Yuj_pUmPmhxEO-KaBf7ZsaLqPLPM',
    appId: '1:959851867881:ios:058cbcc0c31298dc794a78',
    messagingSenderId: '959851867881',
    projectId: 'toy-unity',
    storageBucket: 'toy-unity.appspot.com',
    iosClientId: '959851867881-fc01tsf50ga1p8t34mq0ebln6qeko0mf.apps.googleusercontent.com',
    iosBundleId: 'com.toyunity.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQHC_Yuj_pUmPmhxEO-KaBf7ZsaLqPLPM',
    appId: '1:959851867881:ios:058cbcc0c31298dc794a78',
    messagingSenderId: '959851867881',
    projectId: 'toy-unity',
    storageBucket: 'toy-unity.appspot.com',
    iosClientId: '959851867881-fc01tsf50ga1p8t34mq0ebln6qeko0mf.apps.googleusercontent.com',
    iosBundleId: 'com.toyunity.app',
  );
}
